volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: db

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    container_name: backend

  frontend:
    build: ./frontend/
    env_file: .env
    container_name: frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media
    container_name: gateway